#include <annotate/iofile.h>

/*
 * Generate a vector of gaussian white noise adjusted to a given mean and variance.
 *
 * Vector is generated by the Central Limit Thorem Method, that states that
 * the sum of N randoms will approach normal distribution as N approaches infinity.
 * N is recommended to be >= 20.
 *
 * @reference Jeruchim, "Simulation of communication systems"
 *            1st Ed. Springer, 1992.
 *
 * @arg const double signal[]
 *   Deterministic signal
 * @arg const double mean
 *   Mean value which the vector will be adjusted for
 * @arg const double variance
 *   Variance value which the vector will be adjusted for
 * @arg double* noise
 *   The Gaussian white noise vector
 * @arg int nlen
 *   Length of the gaussian noise vector
 */
void gnoise(const double signal[], const double mean, const double variance, double* noise, int nlen)
{
  double x = 0;
  int i, j;

  for (i = 0; i < nlen; i++) {
    for (j = 0; j < MAX_GNOISE_N; j++) {
      double u = (double) rand() / (double)RAND_MAX;
      x += u;
    }

    // for uniform randoms in [0,1], mu = 0.5 and var = 1/12
    x = x - MAX_GNOISE_N / 2;        // set mean to 0
    x = x * sqrt(12 / MAX_GNOISE_N); // adjust variance to 1

    // modify x in order to have a particular mean and variance
    noise[i] = mean + sqrt(variance) * x;
  }
}

/*
 * wcl
 * 
 * @see src/include/annotate/iofile.h
 */
int wcl (FILE *fp)
{
  int c;        
  int newline_count = 0;

  while ((c=fgetc(fp)) != EOF)
    if ( c == '\n' )
      newline_count++;

  return(newline_count++);
}

/*
 * next_profile
 *
 * @see src/include/annotate/iofile.h
 */
int next_profile(FILE* fp, profile_struct_annotation* profile)
{
  char *line = NULL;
  char *token, *feature, *cline;
  size_t len = 0;
  ssize_t read;
  int i;

  read = getline(&line, &len, fp);

  if (read < 0) {
    free(line);
    return(0);
  }

  cline = (char*) malloc((strlen(line) + 1) * sizeof(char));
  strcpy(cline, line);

  if ((token = strtok(line, "\t")) == NULL) {
    free(cline);
    free(line);
    return(-1);
  }

  if ((feature = strtok(token, ":")) == NULL)  {
    free(cline);
    free(line);
    return(-1);
  }
  strcpy(profile->chromosome, feature);

  if ((feature = strtok(NULL, "-")) == NULL)  {
    free(cline);
    free(line);
    return(-1);
  }
  profile->start = atoi(feature);

  if ((feature = strtok(NULL, ":")) == NULL)  {
    free(cline);
    free(line);
    return(-1);
  }
  profile->end = atoi(feature);
  profile->length = profile->end - profile->start + 1;

  if ((feature = strtok(NULL, ":")) == NULL)  {
    free(cline);
    free(line);
    return(-1);
  }

  if (strcmp(feature, "+") == 0)
    profile->strand = FWD_STRAND;
  else if (strcmp(feature, "-") == 0)
    profile->strand = REV_STRAND;
  else {
    free(cline);
    free(line);
    return(-1);
  }

  profile->additional = 0;

  profile->anscore = INT_MIN;

  profile->profile = (double*) malloc((profile->end - profile->start + 1) * sizeof(double));

  if ((token = strtok(cline, "\t")) == NULL) {
    free(cline);
    free(line);
    return(-1);
  }

  for (i = 0; i < (profile->end - profile->start + 1); i++) {
    if ((token = strtok(NULL, "\t")) != NULL)
      profile->profile[i] = (double) atof(token);
    else {
      free(cline);
      free(line);
      return(-1);
    }
  }

  profile->max_height = gsl_stats_max(profile->profile, 1, profile->length);
  profile->mean = gsl_stats_mean(profile->profile, 1, profile->length);
  profile->variance = gsl_stats_variance(profile->profile, 1, profile->length);
  gnoise(profile->profile, profile->mean, profile->variance, profile->noise, MAX_PROFILE_LENGTH);

  free(cline);
  free(line);
  return(1);
}

/*
 * next_additional_profile
 *
 * @see src/include/annotate/iofile.h
 */
int next_additional_profile(FILE* fp, profile_struct_annotation* profile, char* species)
{
  char *line = NULL;
  char *token, *feature, *cline;
  size_t len = 0;
  ssize_t read;
  int i;

  read = getline(&line, &len, fp);

  if (read < 0) {
    free(line);
    return(0);
  }

  cline = (char*) malloc((strlen(line) + 1) * sizeof(char));
  strcpy(cline, line);

  if ((token = strtok(line, "\t")) == NULL) {
    free(line);
    free(cline);
    return(-1);
  }

  if ((feature = strtok(token, ":")) == NULL)  {
    free(line);
    free(cline);
    return(-1);
  }
  strcpy(profile->chromosome, feature);

  if ((feature = strtok(NULL, "-")) == NULL)  {
    free(line);
    free(cline);
    return(-1);
  }
  profile->start = atoi(feature);

  if ((feature = strtok(NULL, ":")) == NULL)  {
    free(line);
    free(cline);
    return(-1);
  }
  profile->end = atoi(feature);
  profile->length = profile->end - profile->start + 1;

  if ((feature = strtok(NULL, ":")) == NULL)  {
    free(line);
    free(cline);
    return(-1);
  }

  if (strcmp(feature, "+") == 0)
    profile->strand = FWD_STRAND;
  else if (strcmp(feature, "-") == 0)
    profile->strand = REV_STRAND;
  else {
    free(line);
    free(cline);
    return(-1);
  }

  profile->additional = 1;
  strcpy(profile->species, species);

  profile->anscore = INT_MIN;

  profile->profile = (double*) malloc((profile->end - profile->start + 1) * sizeof(double));

  if ((token = strtok(cline, "\t")) == NULL) {
    free(line);
    free(cline);
    return(-1);
  }

  for (i = 0; i < (profile->end - profile->start + 1); i++) {
    if ((token = strtok(NULL, "\t")) != NULL)
      profile->profile[i] = (double) atof(token);
    else {
      free(line);
      free(cline);
      return(-1);
    }
  }

  profile->max_height = gsl_stats_max(profile->profile, 1, profile->length);
  profile->mean = gsl_stats_mean(profile->profile, 1, profile->length);
  profile->variance = gsl_stats_variance(profile->profile, 1, profile->length);
  gnoise(profile->profile, profile->mean, profile->variance, profile->noise, MAX_PROFILE_LENGTH);

  free(line);
  free(cline);
  return(1);
}


/*
 * next_feature
 *
 * @see include/annotate/iofile.h
 */
int next_feature(FILE* bedf, feature_struct* feature)
{
  char *line = NULL;
  char *token, *index;
  size_t len = 0;
  ssize_t read;

  read = getline(&line, &len, bedf);

  if (read < 0)
    return(0);

  if ((token = strtok(line, "\t")) == NULL) 
    return(-1);
  strncpy(feature->chromosome, token, MAX_FEATURE);

  if ((token = strtok(NULL, "\t")) == NULL)
    return(-1);
  feature->start = atoi(token);

  if ((token = strtok(NULL, "\t")) == NULL)
    return(-1);
  feature->end = atoi(token);

  if ((token = strtok(NULL, "\t")) == NULL)
    return(-1);
  strncpy(feature->name, token, MAX_FEATURE);

  if ((token = strtok(NULL, "\t")) == NULL)
    return(-1);

  if ((token = strtok(NULL, "\t")) == NULL)
    return(-1);

  // Check if bed file is BED6 format and remove end of line character
  index = token;
  while(index[1]) ++index;
  if (*index == '\n') *index = '\0';

  if (strcmp(token, "+") == 0) feature->strand = FWD_STRAND;
  else feature->strand = REV_STRAND;

  return(1);
}
